baseURL = "https://www.gauravsood.me"
languageCode = "en-us"
title = "Gaurav Sood"
theme = "cactus"
copyright = "ggsood" 

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Sharing ideas, my thoughts and learnings"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/ggsood" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  # dateFormat = "2020-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ggsood"
  [[params.social]]
    name = "email"
    link = "gauravsood@yahoo.com"  # no need for "mailto:" in the head

# Code Block
pygmentsCodeFences = true
pygmentsStyle = "monokai"
