languageCode: "en-us"
title: "GS"
theme: "crab"
baseurl: "https://www.gauravsood.me/"

params:
  description: "Simple blog site by Gaurav Sood"
# Put the image in the themes/static/images/pic.png location
  # logoimage: "images/pic.ico"

permalinks:
  blog  = "/blog/:year/:month/:title/"

taxonomies:
  tags: "tags"

menu:
  main:
    - weight: 1
      name: Home
      url: /
    - weight: 2
      name: Features
      url: /features/
      identifier: features
    - parent: features
      weight: 1
      name: Responsive design
      url: /features/responsive-design/
    - parent: features
      weight: 2
      name: Nested menus
      url: /features/nested-menus/
      identifier: nested-menus
    - parent: nested-menus
      weight: 1
      name: 'Third level page #1'
      url: /features/nested-menus/third-level-1/
    - parent: nested-menus
      weight: 2
      name: 'Third level page #2'
      url: /features/nested-menus/third-level-2/
    - parent: nested-menus
      weight: 3
      name: 'Third level page #3'
      url: /features/nested-menus/third-level-3/
    - parent: features
      weight: 3
      name: Two-column layout
      url: /features/two-column-layout/
    - parent: features
      weight: 4
      name: Tags
      url: /features/tags/
    - weight: 3
      name: Another item
      url: /another/
    - weight: 4
      name: More items
      url: /more/
      identifier: more
    - parent: more
      weight: 1
      name: Some more menu
      url: /more/some-more-menu/
    - parent: more
      weight: 2
      name: items to show
      url: /more/items-to-show/
    - parent: more
      weight: 3
      name: the nested menus feature
      url: /more/the-nested-menus-feature/
    - weight: 5
      name: Blog
      url: /blog/
    - weight: 6
      name: Contact
      url: /contact/
